
# Obtener terminaciones del editor basado en el esquema de configuraciÃ³n

"$schema" = 'https://starship.rs/config-schema. son'

# Inserta una lÃ­nea en blanco entre las instrucciones del intÃ©rprete de comandos
add_newline = true

# Reemplaza el sÃ­mbolo 'â¯' en el prompt con ''âœ'
[character] # El nombre del mÃ³dulo que estamos configurando es 'character'
success_symbol = '[âœ](bold green)' # El segmento 'success_symbol' se estÃ¡ configurando en 'âœ'  con el color 'bold green'

[git_branch]
symbol = 'ğŸŒ± '
#truncation_length = 8
truncation_symbol = ''

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bold red)'

[git_commit]
commit_hash_length = 4
tag_symbol = 'ğŸ”– '

[git_status]
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'
